In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [5]:
# Main type in NumPy is ndarray. This means an operation done on one array, will work on another

# 1-D array (Vector)
a1 = np.array([1, 2, 3])
print(f"a1:\n{a1}\n")


#2-D array (Matrix)
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
print(f"a2:\n{a2}\n")


# 3-D array (Matrix)
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
print(f"a3:\n{a3}\n")

a1:
[1 2 3]

a2:
[[1.  2.  3.3]
 [4.  5.  6.5]]

a3:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]



In [7]:
# Shows the shape, dimension, data type, size, and type of the array respectively
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [8]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [9]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [ ]:
# Create a simple array
a1 = np.array[1, 2, 3]