In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [2]:
# Main type in NumPy is ndarray. This means an operation done on one array, will work on another

# 1-D array (Vector)
a1 = np.array([1, 2, 3])
print(f"a1:\n{a1}\n")


#2-D array (Matrix)
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
print(f"a2:\n{a2}\n")


# 3-D array (Matrix)
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
print(f"a3:\n{a3}\n")

a1:
[1 2 3]

a2:
[[1.  2.  3.3]
 [4.  5.  6.5]]

a3:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]



In [3]:
# Shows the shape, dimension, data type, size, and type of the array respectively
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [5]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [6]:
# Create a simple array
A1 = np.array([1, 2, 3])

In [7]:
# Use the array functions and list the details of this array
A1.shape, A1.ndim, A1.dtype, A1.size, type(A1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [8]:
# Create an array of ones
ones = np.ones([3, 3])
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# Cast the created array into another dtype using .astype("dtype")
ones.astype("int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
# Create an array of zeros
zeros = np.zeros([3, 3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# Create an array within a range of values
range = np.random.randint(5, 10, size=5)
print(range)

[6 5 6 8 8]


In [12]:
# Random array
random = np.random.randint(10, size=5)
print(random)

[1 2 8 6 1]


In [13]:
# Random array of floats
floats = np.random.rand(10) 
print(floats)

[0.82667115 0.51159558 0.84543716 0.40745264 0.16941591 0.58244864
 0.46747048 0.53738849 0.27543149 0.62468855]


In [14]:
# Set random seed to 0
np.random.seed(1)

In [15]:
# Make more random numbers
np.random.randint(10, size=(5, 3))

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

In [16]:
# Set random seed to same number as above
np.random.seed(1)

In [17]:
# The same numbers come out
np.random.randint(10, size=(5, 3))

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

In [21]:
# Finding unique values in a numpy array
np.unique(a3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [26]:
# Array shapes are always listed in the format (row, column, n, n, n.....) where n is optimal extra dimensions
a1[0]

1

In [27]:
a2[0]

array([1. , 2. , 3.3])

In [28]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# Get 2nd row (index 1) of a2
a2[1]

array([4. , 5. , 6.5])

In [31]:
# Get the first 2 values of the first 2 rows of both arrays
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [33]:
# NumPy arrays get printed from outside to inside. This means the number at the end o the shape comes first, and the number at the start of the shape comes last.
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[0, 6, 5, 1, 2],
         [1, 5, 4, 0, 7],
         [8, 9, 5, 7, 0],
         [9, 3, 9, 1, 4]],

        [[4, 6, 8, 8, 9],
         [2, 7, 5, 5, 4],
         [5, 8, 5, 8, 1],
         [1, 8, 7, 0, 3]],

        [[4, 2, 0, 3, 5],
         [1, 2, 4, 3, 0],
         [6, 0, 7, 2, 8],
         [3, 0, 8, 4, 2]]],


       [[[9, 0, 3, 8, 1],
         [4, 3, 3, 6, 7],
         [3, 5, 3, 2, 4],
         [4, 0, 3, 3, 8]],

        [[3, 5, 6, 7, 5],
         [1, 7, 0, 2, 8],
         [2, 1, 4, 0, 4],
         [1, 7, 3, 1, 6]],

        [[6, 9, 6, 9, 6],
         [0, 0, 2, 9, 6],
         [0, 6, 7, 0, 3],
         [9, 0, 3, 4, 7]]]])

In [35]:
a4.shape

(2, 3, 4, 5)

In [36]:
# Get onlt the first 4 numbers of each single vector
a4[:, :, :, :4]

array([[[[0, 6, 5, 1],
         [1, 5, 4, 0],
         [8, 9, 5, 7],
         [9, 3, 9, 1]],

        [[4, 6, 8, 8],
         [2, 7, 5, 5],
         [5, 8, 5, 8],
         [1, 8, 7, 0]],

        [[4, 2, 0, 3],
         [1, 2, 4, 3],
         [6, 0, 7, 2],
         [3, 0, 8, 4]]],


       [[[9, 0, 3, 8],
         [4, 3, 3, 6],
         [3, 5, 3, 2],
         [4, 0, 3, 3]],

        [[3, 5, 6, 7],
         [1, 7, 0, 2],
         [2, 1, 4, 0],
         [1, 7, 3, 1]],

        [[6, 9, 6, 9],
         [0, 0, 2, 9],
         [0, 6, 7, 0],
         [9, 0, 3, 4]]]])